import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Provider from "@/utils/Providers";
import LoadingPage from "@/components/global/modal/loadingPage";
import NotificationPage from "@/components/global/modal/notif";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ["nextjs", "react", "formik", "typescript", "yup", "react query"],
};

interface Root {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<Root>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider>
          {children}
          <LoadingPage />
          <NotificationPage />
        </Provider>
      </body>
    </html>
  );
}
